//Random whitespace is tested throughout including spaces, tabs, returns

//Test Reserved Words
//testing reserved words in all lowercase and then all uppercase ensures that I've
//correctly defined them (and didn't make any typos.  There is no need to test
//more than just a few with mixed case because of this.
class CLASS cLaSs ClAsS
bool BOOL
char CHAR
int INT
const              CONST
if      IF
else ELSE
true TRUE
false FALSE
while WHILE
continue CONTINUE
break BREAK
read READ
print PRINT
return RETURN
void VOID

//Test Identifiers // //
AWord tmpLine t T t1     ThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPasteThisIsAVeryLongIdentifierThatIsHopefullyGoingToBeRecognizedByTheSystemAndNotHaveProblemsCuzIfItHasProblemsThenIHaveAProblemABigProblemSoIReallyHopeThatItWorksCorrectlyTheFirstTimeAroundOtherwiseIllHaveToDebugItAndIReallyDontWantToDebugSomethingAsRediculouslyLongAsThisStringGahImGettingCloseToAReallyLongIdentifierSoIShallStopSoonBecauseMyPinkyIsGettingTiredFromPushingShiftSoOftenToTypeThisCrazyLongIdentifierWoahIJustHitCtrlDeleteToDeleteTheLastWordAndMyWholeStringWentBoyWasIScaredIdNeverWantToHaveToDoThisAgainOkayNowTheStringWillRepeatDueToCopyAndPaste
strTemp more2Idents90832 a  f B  E  z
ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
a0123456789

//Test illegal Identifiers
super! 1t
myCount. temp$ var_  jie~ ji`
bni@ muiol#  ijljli%  fiid^  fiji&
ille\gal

//Test Integer Literals
2342
21342345623434634534
~23423423423423423433
1234567890
~1234567890
~1
-1
1
0

//Test String Literals
"string literal includes: \" \n \t \\"
"mom"
"bool"
"string!@#$%^&*()_+[]{}|:;';'\""



//Test Character Literals
'a' 'A' 'z' 'Z' 'c' 'E' '\n' '\t'
'\\'
'\''
'"'
'$' '^' '*' '+' '-'


//test other tokens
()[]=;+-*/==!=&&++--||<><=>=,!{}:
=====


//Test comments // //////////////////////
///////////////////////////////////////////////////////////////////////
####
##comment
## testvar///
//previous variable testvar should be correctly defined
//all the rest should be comments
//////
//////
///asdfjkalsdf
##;kjbvklj;asj;;aklwe
!@#$%&*()_+}|{P":?##
##jklsjdaklfjasl;dfjaklsd;#dlfksjaklsdfjkLD##
//lkdjfakkljaslkdfj##

//test illegal Char Literals
'\'
'\d'
'dd'

    //test invalid literals
    "strings don't include \ a single slash"
    "\012jivasdf"
    //test unclosed string
    "
this is not a continuation "const"
