
//----------------------------------------------------
// The following code was generated by CUP v0.10f
// Wed Apr 15 14:15:57 CDT 2015
//----------------------------------------------------

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int STRLIT = 45;
  static final int rw_WHILE = 42;
  static final int rw_BOOL = 16;
  static final int LBRACKET = 24;
  static final int INCREMENT = 27;
  static final int rw_IF = 14;
  static final int SLASH = 20;
  static final int rw_CONTINUE = 44;
  static final int rw_FALSE = 40;
  static final int LPAREN = 5;
  static final int SEMI = 4;
  static final int rw_PRINT = 41;
  static final int rw_TRUE = 35;
  static final int MINUS = 11;
  static final int DECREMENT = 28;
  static final int RPAREN = 6;
  static final int NOT = 17;
  static final int rw_VOID = 36;
  static final int INTLIT = 3;
  static final int LT = 22;
  static final int rw_CONST = 39;
  static final int COMMA = 19;
  static final int rw_ELSE = 33;
  static final int GEQ = 30;
  static final int PLUS = 10;
  static final int rw_READ = 34;
  static final int rw_INT = 15;
  static final int EOF = 0;
  static final int RBRACKET = 25;
  static final int error = 1;
  static final int COR = 31;
  static final int rw_CLASS = 38;
  static final int rw_RETURN = 43;
  static final int EQ = 12;
  static final int ASG = 7;
  static final int TIMES = 18;
  static final int CHARLIT = 46;
  static final int COLON = 21;
  static final int LBRACE = 8;
  static final int rw_CHAR = 32;
  static final int RBRACE = 9;
  static final int CAND = 26;
  static final int LEQ = 29;
  static final int rw_BREAK = 37;
  static final int GT = 23;
  static final int NOTEQ = 13;
  static final int IDENTIFIER = 2;
}

